dnl @@
dnl    @file      configure.in
dnl    @date      Sun Jan 17 15:54:23 1999
dnl    @author    Tom Goodale
dnl    @desc 
dnl    
dnl    @enddesc 
dnl    @version $Id$
dnl  @@
dnl Process this file with autoconf to produce a configure script.

AC_REVISION($Id$)
AC_INIT()
AC_CONFIG_HEADER(config.h)

dnl Check the system type
AC_CANONICAL_SYSTEM

dnl Checks for programs.
AC_PROG_MAKE_SET
AC_PROG_CC
AC_PROG_CXX
AC_PROG_RANLIB
dnl Look for a standalone CPP
AC_PATH_PROGS(CPP, cpp, echo, /lib:/usr/lib:/usr/local/lib:$PATH)

AC_PATH_PROGS(PERL, perl)
AC_PATH_PROGS(F90, f90 pgf90)
AC_PATH_PROGS(F77, f77 pgf77 g77 f90 pgf90)
AC_PATH_PROGS(AR, ar)
AC_PATH_PROGS(MKDIR, mkdir)
AC_PATH_PROGS(SHELL, sh bash)

AC_SUBST(LD)
LD=$CXX

dnl Checks for libraries.

dnl Checks for header files.

dnl Checks for typedefs, structures, and compiler characteristics.

AC_C_BIGENDIAN
AC_C_CONST
AC_C_INLINE
AC_C_LONG_DOUBLE
AC_CHECK_SIZEOF(int)
AC_CHECK_SIZEOF(short int)
AC_CHECK_SIZEOF(char *)

AC_SUBST(ARFLAGS)
ARFLAGS=rucs

AC_SUBST(F90FLAGS)
AC_SUBST(F77FLAGS)

: ${F90FLAGS=$CFLAGS}
: ${F77FLAGS=$CFLAGS}

dnl Checks for library functions.

dnl Misc stuff

AC_SUBST(LIBDIRS)

AC_SUBST(PACKAGE_DIR)
AC_SUBST(BUILD_DIR)
AC_SUBST(CCTK_LIBDIR)
AC_SUBST(EXE)

: ${PACKAGE_DIR=packages}
: ${BUILD_DIR=build}
: ${CCTK_LIBDIR=lib}

# The perl scripts run by the make system need to have their names
# changed if under cygwin - e.g. //d/foo needs to be d:/foo

PERL_CONFIGURE_SCRIPT=`echo $srcdir/configure.pl | sed 's,^//\(.\)/,\1:/,'`

AC_SUBST(BUILD_ACTIVETHORNS)
BUILD_ACTIVETHORNS=`echo $srcdir/../sbin/BuildActiveThorns.pl | sed 's,^//\(.\)/,\1:/,'`
AC_SUBST(CST)
CST=`echo $srcdir/../sbin/CST | sed 's,^//\(.\)/,\1:/,'`

AC_SUBST(F_FILE_PROCESSOR)
F_FILE_PROCESSOR=`echo $srcdir/../sbin/f_file_processor.pl | sed 's,^//\(.\)/,\1:/,'`
AC_SUBST(C_FILE_PROCESSOR)
C_FILE_PROCESSOR=`echo $srcdir/../sbin/c_file_processor.pl | sed 's,^//\(.\)/,\1:/,'`

# Deal with the Fortran compiler issues.
# If there's a Fortran 90 compiler use that for all the Fortran.
if test "x$F90" != "x" ; then
F77=$F90 
F77FLAGS=$F90FLAGS ;
fi


# If this is a known architecture, setup any specific flags

if test -r $srcdir/known-architectures/$host_os ; then
. $srcdir/known-architectures/$host_os
fi

dnl Run any other scripts necessary

AC_OUTPUT_COMMANDS(,$PERL -s $PERL_CONFIGURE_SCRIPT -compiler="$F77" -opts="$F77FLAGS" .) 

dnl Output everything
AC_OUTPUT(make.config.defn make.config.deps make.config.rules)
