#! /usr/bin/perl -s
#/*@@
#  @file      setup
#  @date      Fri Jan  8 13:48:48 1999
#  @author    Tom Goodale
#  @desc 
#  Prototype setup file for the CCTK
#  @enddesc 
#  @version $Id$
#@@*/

$top = `pwd`;

chop $top;

$configure = "$top/lib/make/configure";

$uname = `uname`;

$uname =~ s/(sn\d\d\d\d|jsimpson)/UNICOS\/mk/;

chop $uname;

if($#ARGV > 0)
{
  $config = shift(@ARGV);
}
else
{
  $config = $uname;
}

# The build directory doesn't exist.
if (! -d "build" && ! -l "build")
{
  print "Completely new cactus build.  Creating config database\n";

  mkdir("build", 0755)
  
}

chdir build;

# The specified configuration doesn't exist
if (! -d "$config" && ! -l "$config")
{
  print "Creating new configuration $config.\n";

  mkdir("$config",0755);

  chdir "$config";

  mkdir("build",0755);
  mkdir("lib",0755);
  mkdir("config-data",0755);
  mkdir("libraries",0755);

  chdir "config-data";

  $ENV{"EXE"} = "cctk";

  system("$configure");
  chdir "..";
  chdir "..";
}

# Rerun the configure script
if($reconfig)
{
  print "Reconfiguring $config.\n";

  chdir "$config";

  chdir "config-data";

  $ENV{"EXE"} = "cctk";

  system("$configure");
  chdir "..";
  chdir "..";
}
