#! /bin/sh
# Create all arrangement documentations
# (C) 2003-07-21 Erik Schnetter <schnetter@uni-tuebingen.de>
# $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/sbin/ArrangementDoc,v 1.3 2005-06-18 13:06:08 schnetter Exp $

echo "Creating arrangement documentations..."

# Selected arrangement; process all arrangements if this is empty
selection="$1"

for arr in `cd arrangements; echo *`; do
    if test -d arrangements/$arr; then
        if test -z "$selection" || test "$arr" == "$selection"; then
            if test -e arrangements/$arr/doc/documentation.tex; then
                echo "  Processing arrangement $arr..."
                
                mkdir doc/ArrangementDoc 2> /dev/null
                mkdir doc/ArrangementDoc/$arr 2> /dev/null
                (
                    cd doc/ArrangementDoc/$arr/$th
                    rm -f documentation.tex documentation.dvi documentation.ps
                    path=../../../arrangements/$arr/$th/doc
                    sed -e 's+\(\\includegraphics.*\){ *\(.*\) *}+\1{'"$path"'/\2}+g' < $path/documentation.tex > documentation.tex
                    
                    {
                        latex documentation < /dev/null > LATEX_MESSAGES 2>&1
                        latex documentation < /dev/null > LATEX_MESSAGES 2>&1
                        latex documentation < /dev/null > LATEX_MESSAGES 2>&1 &&
                        dvips documentation.dvi -o documentation.ps > DVIPS_MESSAGES 2>&1
                    } ||
                    echo "    ERROR: Could not create documentation (check for latex errors)"
                )
                
            fi                  # if arrangement has documentation
        fi                      # if arrangement is enabled
    fi
done                            # for arrangements

echo "  Created arrangement documentations in doc/ArrangementDoc directory."
echo "  Done."
