#! /bin/sh

if [ ! -n "$1" ]
then
  figpath="."
else
 figpath=$1
fi

files=`find ${figpath} -type f -name "*.pdf"`

if [ -n "${files}" ]; then
  echo "  Converting figures to postscript"
fi

# name of Ghostscript interpreter command
GS=gs

for i in $files; do
  epsfilename=`echo $i | sed s/.pdf$/.eps/`
  if [ "$i" != "documentation.pdf" ] && [ ! -e $epsfilename ]; then
    echo "   " `basename $i` " -> " `basename $epsfilename`
    $GS -q -dNOCACHE -dNOPAUSE -dBATCH -dSAFER -sDEVICE=eps2write -sOutputFile=$epsfilename $i
  fi
done
