#! /bin/sh
# Create all thorn documentations
# (C) 2003/05/24 Erik Schnetter <schnetter@uni-tuebingen.de>
# $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/sbin/ThornDoc,v 1.3 2009-01-26 23:27:49 schnetter Exp $

echo "Creating thorn documentations..."

# Selected thorn; process all thorns if this is empty
selection="$1"

for arr in `cd arrangements; echo *`; do
    if test -d arrangements/$arr; then
        for th in `cd arrangements/$arr; echo *`; do
            if test -d arrangements/$arr/$th; then
                if test -z "$selection" || test "$th" == "$selection"; then
                    if test -e arrangements/$arr/$th/doc/documentation.tex; then
                        echo "  Processing thorn $arr/$th..."
                        
                        mkdir doc/ThornDoc 2> /dev/null
                        mkdir doc/ThornDoc/$arr 2> /dev/null
                        mkdir doc/ThornDoc/$arr/$th 2> /dev/null
                        (
                            cd doc/ThornDoc/$arr/$th
                            rm -f documentation.tex documentation.dvi documentation.ps
                            path=../../../../arrangements/$arr/$th/doc
                            sed -e 's+\(\\includegraphics.*\){ *\(.*\) *}+\1{'"$path"'/\2}+g' < $path/documentation.tex > documentation.tex
                            
                            {
                                pdflatex documentation < /dev/null > LATEX_MESSAGES 2>&1
                                pdflatex documentation < /dev/null > LATEX_MESSAGES 2>&1
                                pdflatex documentation < /dev/null > LATEX_MESSAGES 2>&1
                            } ||
                            echo "    ERROR: Could not create documentation (check for latex errors)"
                        )
                        
                    fi          # if thorn has documentation
                fi              # if thorn is enabled
            fi
        done                    # for thorns
    fi
done                            # for arrangements

echo "  Created thorn documentations in doc/ThornDoc directory."
echo "  Done."
