#! /bin/sh
# /*@@
#   @file      LAM
#   @date      Wed Jul 21 13:27:07 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/LAM,v 1.3 2000-10-15 17:21:52 tradke Exp $ 
# @@*/

echo "LAM selected"

if test -z "$LAM_LIB_DIR" -o -z "$LAM_INC_DIR" ; then
  if test -z "$LAM_DIR" ; then
     echo "LAM selected but no LAM_DIR set... Checking some places"
     CCTK_Search LAM_DIR "/usr /usr/local /usr/local/lam /usr/local/packages/lam /usr/local/apps/lam" h/lam.h
     if test -z "$LAM_DIR" ; then
       echo "Unable to locate the LAM directory - please set LAM_DIR"
       exit 2
     fi
  fi
  LAM_LIB_DIR="$LAM_DIR/lib"
  LAM_INC_DIR="$LAM_DIR/h"
fi

MPI_LIBS="mpi tstdio args t trillium " 
MPI_LIB_DIRS="$LAM_LIB_DIR"
MPI_INC_DIRS="$LAM_INC_DIR"
