#! /bin/sh
# /*@@
#   @file      NATIVE
#   @date      Wed Jul 21 13:27:07 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/NATIVE,v 1.2 1999-07-21 12:52:55 goodale Exp $ 
# @@*/

echo "Native MPI selected"

# This should be filled out by the know-architecture stuff.

: ${MPI_LIBS=""} 
: ${MPI_LIB_DIRS=""}
: ${MPI_INC_DIRS=""}
