# Autogenerated code, created by ReParse. Do not edit.
use strict;

use piraha;



sub reparserGenerator() {
  my $g = new Grammar();
  $g->{patterns}->{"boundary"}=(new Seq(
    new Literal("\\"),
    new Literal('b')));
  $g->{patterns}->{"backref"}=(new Seq(
    new Literal("\\"),
    (new Bracket(0))
      ->addRange('1','9')
      ));
  $g->{patterns}->{"named"}=(new Seq(
    new Literal('{'),
    new Lookup("name",$g),
    new Literal('}')));
  $g->{patterns}->{"echar"}=(new Literal('-'));
  $g->{patterns}->{"num"}=(new Multi((new Bracket(0))
    ->addRange('0','9')
    ,1,2147483647));
  $g->{patterns}->{"dot"}=(new Literal('.'));
  $g->{patterns}->{"pattern"}=(new Seq(
    new Start(),
    new Or(
      new Lookup("group_inside",$g),
      new Nothing()),
    new End()));
  $g->{patterns}->{"range"}=(new Seq(
    new Lookup("cchar",$g),
    new Literal('-'),
    new Lookup("cchar",$g)));
  $g->{patterns}->{"literal"}=(new Or(
    new Seq(
      new Literal("\\"),
      new Literal('u'),
      new Lookup("hex",$g)),
    new Seq(
      new Literal("\\"),
      (new Bracket(1))
        ->addRange('b','b')
        ),
    (new Bracket(1))
      ->addRange('$','$')
      ->addRange('(','+')
      ->addRange('.','.')
      ->addRange('?','?')
      ->addRange('[','^')
      ->addRange('{','}')
      ));
  $g->{patterns}->{"neg"}=(new Literal('^'));
  $g->{patterns}->{"cchar"}=(new Or(
    new Seq(
      new Literal("\\"),
      new Literal('u'),
      new Lookup("hex",$g)),
    new Seq(
      new Literal("\\"),
      (new Bracket(1))
        ),
    (new Bracket(1))
      ->addRange('-','-')
      ->addRange("\\",']')
      ));
  $g->{patterns}->{"hex"}=(new Multi((new Bracket(0))
    ->addRange('0','9')
    ->addRange('A','F')
    ->addRange('a','f')
    ,4,4));
  $g->{patterns}->{"pipe"}=(new Nothing());
  $g->{patterns}->{"end"}=(new Literal('$'));
  $g->{patterns}->{"group"}=(new Seq(
    new Literal('('),
    new Or(
      new Lookup("ign_on",$g),
      new Lookup("ign_off",$g),
      new Lookup("lookahead",$g),
      new Lookup("neglookahead",$g),
      new Nothing()),
    new Or(
      new Lookup("group_inside",$g),
      new Nothing()),
    new Literal(')')));
  $g->{patterns}->{"ign_on"}=(new Seq(
    new Literal('?'),
    new Literal('i'),
    new Literal(':')));
  $g->{patterns}->{"pelem"}=(new Or(
    new Seq(
      new Or(
        new Lookup("named",$g),
        new Lookup("dot",$g),
        new Lookup("backref",$g),
        new Lookup("literal",$g),
        new Lookup("charclass",$g),
        new Lookup("group",$g)),
      new Or(
        new Lookup("quant",$g),
        new Nothing())),
    new Or(
      new Lookup("start",$g),
      new Lookup("end",$g),
      new Lookup("boundary",$g))));
  $g->{patterns}->{"nothing"}=(new Nothing());
  $g->{patterns}->{"group_inside"}=(new Seq(
    new Lookup("pelems",$g),
    new Multi(new Seq(
      new Literal('|'),
      new Lookup("pelems",$g)),0,2147483647),
    new Or(
      new Seq(
        new Lookup("nothing",$g),
        new Literal('|')),
      new Nothing())));
  $g->{patterns}->{"start"}=(new Literal('^'));
  $g->{patterns}->{"quantmax"}=(new Seq(
    new Literal(','),
    new Multi(new Lookup("num",$g),0,1)));
  $g->{patterns}->{"ign_off"}=(new Seq(
    new Literal('?'),
    new Literal('-'),
    new Literal('i'),
    new Literal(':')));
  $g->{patterns}->{"quant"}=(new Or(
    new Literal('+'),
    new Literal('*'),
    new Literal('?'),
    new Seq(
      new Literal('{'),
      new Lookup("num",$g),
      new Multi(new Lookup("quantmax",$g),0,1),
      new Literal('}'))));
  $g->{patterns}->{"lookahead"}=(new Seq(
    new Literal('?'),
    new Literal('=')));
  $g->{patterns}->{"pelems"}=(new Seq(
    new Lookup("pelem",$g),
    new Multi(new Lookup("pelem",$g),0,2147483647)));
  $g->{patterns}->{"name"}=(new Seq(
    new Multi(new Literal('-'),0,1),
    (new Bracket(0))
      ->addRange(':',':')
      ->addRange('A','Z')
      ->addRange('_','_')
      ->addRange('a','z')
      ,
    new Multi((new Bracket(0))
      ->addRange('0',':')
      ->addRange('A','Z')
      ->addRange('_','_')
      ->addRange('a','z')
      ,0,2147483647)));
  $g->{patterns}->{"charclass"}=(new Seq(
    new Literal('['),
    new Multi(new Lookup("neg",$g),0,1),
    new Multi(new Or(
      new Lookup("range",$g),
      new Lookup("echar",$g)),0,1),
    new Multi(new Or(
      new Lookup("range",$g),
      new Lookup("cchar",$g)),0,2147483647),
    new Multi(new Lookup("echar",$g),0,1),
    new Literal(']')));
  $g->{patterns}->{"neglookahead"}=(new Seq(
    new Literal('?'),
    new Literal('!')));
  return $g;
}


sub fileparserGenerator() {
  my $g = new Grammar();
  $g->{patterns}->{"boundary"}=(new Seq(
    new Literal("\\"),
    new Literal('b')));
  $g->{patterns}->{"backref"}=(new Seq(
    new Literal("\\"),
    (new Bracket(0))
      ->addRange('1','9')
      ));
  $g->{patterns}->{"named"}=(new Seq(
    new Literal('{'),
    new Lookup("name",$g),
    new Literal('}')));
  $g->{patterns}->{"echar"}=(new Literal('-'));
  $g->{patterns}->{"num"}=(new Multi((new Bracket(0))
    ->addRange('0','9')
    ,1,2147483647));
  $g->{patterns}->{"dot"}=(new Literal('.'));
  $g->{patterns}->{"pattern"}=(new Or(
    new Lookup("group_top",$g),
    new Nothing()));
  $g->{patterns}->{"range"}=(new Seq(
    new Lookup("cchar",$g),
    new Literal('-'),
    new Lookup("cchar",$g)));
  $g->{patterns}->{"rule"}=(new Seq(
    new Lookup("name",$g),
    new Lookup("-w",$g),
    new Literal('='),
    new Lookup("-w",$g),
    new Lookup("pattern",$g)));
  $g->{patterns}->{"pelems_next"}=(new Seq(
    new Multi(new Lookup("s",$g),0,1),
    new Literal('|'),
    new Multi(new Lookup("s",$g),0,1),
    new Lookup("pelem",$g),
    new Multi(new Seq(
      new Multi(new Lookup("s0",$g),0,1),
      new Lookup("pelem",$g)),0,2147483647)));
  $g->{patterns}->{"literal"}=(new Or(
    new Seq(
      new Literal("\\"),
      new Literal('u'),
      new Lookup("hex",$g)),
    new Seq(
      new Literal("\\"),
      (new Bracket(1))
        ->addRange('1','9')
        ->addRange('b','b')
        ),
    (new Bracket(1))
      ->addRange("\n","\n")
      ->addRange("\r","\r")
      ->addRange('$','$')
      ->addRange('(','+')
      ->addRange('.','.')
      ->addRange('?','?')
      ->addRange('[','^')
      ->addRange('{','}')
      ));
  $g->{patterns}->{"neg"}=(new Literal('^'));
  $g->{patterns}->{"file"}=(new Seq(
    new Start(),
    new Multi(new Lookup("-s",$g),0,1),
    new Lookup("rule",$g),
    new Multi(new Seq(
      new Multi(new Lookup("-s",$g),0,1),
      new Lookup("rule",$g)),0,2147483647),
    new Multi(new Lookup("-s",$g),0,1),
    new End()));
  $g->{patterns}->{"cchar"}=(new Or(
    new Seq(
      new Literal("\\"),
      new Literal('u'),
      new Lookup("hex",$g)),
    new Seq(
      new Literal("\\"),
      (new Bracket(1))
        ),
    (new Bracket(1))
      ->addRange('-','-')
      ->addRange("\\",']')
      ));
  $g->{patterns}->{"hex"}=(new Multi((new Bracket(0))
    ->addRange('0','9')
    ->addRange('A','F')
    ->addRange('a','f')
    ,4,4));
  $g->{patterns}->{"pipe"}=(new Nothing());
  $g->{patterns}->{"end"}=(new Literal('$'));
  $g->{patterns}->{"s0"}=(new Multi((new Bracket(0))
    ->addRange("\t","\t")
    ->addRange(' ',' ')
    ,1,2147483647));
  $g->{patterns}->{"pelems_top"}=(new Seq(
    new Lookup("pelem",$g),
    new Multi(new Seq(
      new Multi(new Lookup("s0",$g),0,1),
      new Lookup("pelem",$g)),0,2147483647)));
  $g->{patterns}->{"group"}=(new Seq(
    new Literal('('),
    new Or(
      new Lookup("ign_on",$g),
      new Lookup("ign_off",$g),
      new Lookup("lookahead",$g),
      new Lookup("neglookahead",$g),
      new Nothing()),
    new Or(
      new Lookup("group_inside",$g),
      new Nothing()),
    new Literal(')')));
  $g->{patterns}->{"ign_on"}=(new Seq(
    new Literal('?'),
    new Literal('i'),
    new Literal(':')));
  $g->{patterns}->{"pelem"}=(new Or(
    new Seq(
      new Or(
        new Lookup("named",$g),
        new Lookup("dot",$g),
        new Lookup("backref",$g),
        new Lookup("literal",$g),
        new Lookup("charclass",$g),
        new Lookup("group",$g)),
      new Or(
        new Lookup("quant",$g),
        new Nothing())),
    new Or(
      new Lookup("start",$g),
      new Lookup("end",$g),
      new Lookup("boundary",$g))));
  $g->{patterns}->{"nothing"}=(new Nothing());
  $g->{patterns}->{"group_inside"}=(new Seq(
    new Lookup("pelems",$g),
    new Multi(new Seq(
      new Literal('|'),
      new Lookup("pelems",$g)),0,2147483647),
    new Or(
      new Seq(
        new Multi(new Lookup("s0",$g),0,1),
        new Lookup("nothing",$g),
        new Literal('|')),
      new Nothing()),
    new Multi(new Lookup("s",$g),0,1)));
  $g->{patterns}->{"start"}=(new Literal('^'));
  $g->{patterns}->{"quantmax"}=(new Seq(
    new Literal(','),
    new Multi(new Lookup("num",$g),0,1)));
  $g->{patterns}->{"ign_off"}=(new Seq(
    new Literal('?'),
    new Literal('-'),
    new Literal('i'),
    new Literal(':')));
  $g->{patterns}->{"quant"}=(new Or(
    new Literal('+'),
    new Literal('*'),
    new Literal('?'),
    new Seq(
      new Literal('{'),
      new Lookup("num",$g),
      new Multi(new Lookup("quantmax",$g),0,1),
      new Literal('}'))));
  $g->{patterns}->{"lookahead"}=(new Seq(
    new Literal('?'),
    new Literal('=')));
  $g->{patterns}->{"s"}=(new Multi(new Or(
    (new Bracket(0))
      ->addRange("\t","\n")
      ->addRange("\r","\r")
      ->addRange(' ',' ')
      ,
    new Seq(
      new Literal('#'),
      new Multi(new Dot(),0,2147483647))),1,2147483647));
  $g->{patterns}->{"pelems"}=(new Seq(
    new Multi(new Seq(
      new Multi(new Lookup("s",$g),0,1),
      new Lookup("pelem",$g)),1,2147483647),
    new Multi(new Lookup("s",$g),0,1)));
  $g->{patterns}->{"group_top"}=(new Seq(
    new Lookup("pelems_top",$g),
    new Multi(new Lookup("pelems_next",$g),0,2147483647),
    new Or(
      new Seq(
        new Multi(new Lookup("s",$g),0,1),
        new Lookup("nothing",$g),
        new Literal('|')),
      new Nothing())));
  $g->{patterns}->{"w"}=(new Multi((new Bracket(0))
    ->addRange("\t","\t")
    ->addRange(' ',' ')
    ,0,2147483647));
  $g->{patterns}->{"name"}=(new Seq(
    new Multi(new Literal('-'),0,1),
    (new Bracket(0))
      ->addRange(':',':')
      ->addRange('A','Z')
      ->addRange('_','_')
      ->addRange('a','z')
      ,
    new Multi((new Bracket(0))
      ->addRange('0',':')
      ->addRange('A','Z')
      ->addRange('_','_')
      ->addRange('a','z')
      ,0,2147483647)));
  $g->{patterns}->{"charclass"}=(new Seq(
    new Literal('['),
    new Multi(new Lookup("neg",$g),0,1),
    new Multi(new Or(
      new Lookup("range",$g),
      new Lookup("echar",$g)),0,1),
    new Multi(new Or(
      new Lookup("range",$g),
      new Lookup("cchar",$g)),0,2147483647),
    new Multi(new Lookup("echar",$g),0,1),
    new Literal(']')));
  $g->{patterns}->{"neglookahead"}=(new Seq(
    new Literal('?'),
    new Literal('!')));
  return $g;
}
1;
