#! /bin/sh
#  /*@@
#    @file      aix
#    @date      Wed Jul 14 12:38:45 1999
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header$
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${F90FLAGS="-g -O2 -qfixed"}
  : ${F77FLAGS="-g -O2 -qfixed"}

  : ${C_DEPEND_OUT=' > $@'}
  : ${CXX_DEPEND_OUT=' > $@'}
  : ${F_DEPEND_OUT=' > /dev/null ; mv $(basename $(basename $@)).u $@'}
  : ${F77_DEPEND_OUT=' > /dev/null ; mv $(basename $(basename $@)).u $@'}

  : ${LIBS="xlf90"}


  # MPI stuff
 
  if test -n "$MPI" ; then
      NATIVE_MPI_LIBS="mpi"
      NATIVE_MPI_LIB_DIRS="/usr/lpp/ppe.poe/lib"
      NATIVE_MPI_INC_DIRS="/usr/lpp/ppe.poe/include"
  fi          

fi
