#! /bin/sh
# /*@@
#   @file      hiuxmpp
#   @date      Wed Apr 19 17:58:22 2000
#   @author    Tom Goodale
#   @desc  Optimazations by Peter Diener
#   Configuration file for the Hitachi SR8000-F1
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/hiuxmpp,v 1.6 2001-04-05 14:36:15 tradke Exp $
# @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

  #
  # use the native compilers by default
  #
  if test -z "$CC"; then
    echo Setting C compiler to cc
    CC="cc"
  fi

  if test -z "$CXX"; then
    echo Setting C++ compiler to CC
    CXX="CC"
  fi

  if test -z "$LD"; then
    echo Setting linker to CC
    LD="CC"
  fi

else

  CFLAGS="$CFLAGS -64"
  CXXFLAGS="$CXXFLAGS -64"

  : ${F77FLAGS="-64 -conti199 -uinline=2"}
  : ${F90FLAGS="-64 -conti199 -uinline=2"}

  LDFLAGS="$LDFLAGS -64"

  : ${C_OPTIMISE_FLAGS="-O4 -pvec -pvfunc -predicate -model=F1"}
#  : ${CXX_OPTIMISE_FLAGS="-O4 -pvec -pvfunc -predicate -model=F1"}

  : ${F77_OPTIMISE_FLAGS="-opt=ss -pvfunc=2 -noparallel -model=F1"}
  : ${F90_OPTIMISE_FLAGS="-opt=ss -pvfunc=2 -noparallel -model=F1 -noscope"}

# No way to generate dependencies on this machine.
  : ${C_DEPEND="echo"}
  : ${CXX_DEPEND="echo"}
  : ${F_DEPEND="echo"}
  : ${F77_DEPEND="echo"}

  : ${C_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${CXX_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${F_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${F77_DEPEND_OUT='>/dev/null ; touch $@'}

# Yet another CXX->C translator 8-(.
  : ${CXX_WORKING_NAME='$(notdir $<)'}

  : ${CXX_POSTPROCESSING='if test -r $(SCRATCH_BUILD)$(DIRSEP)$(basename $(basename $(notdir $@))).o ; then cp $(SCRATCH_BUILD)$(DIRSEP)$(basename $(basename $(notdir $@))).o $@ ; fi'}

  : ${LIBS="f90s f90 hf90pvmath hf90math m"}

  : ${L2_CACHELINE_BYTES="128"}
  : ${L2_CACHE_SIZE="128*1024"}

# MPI stuff

  if test -n "$MPI" ; then
    NATIVE_MPI_LIBS="mpi"
    NATIVE_MPI_LIB_DIRS="/usr/mpi/lib/lib64"
    NATIVE_MPI_INC_DIRS="/usr/mpi/include"
  fi

# PTHREADS stuff

  if test "X$PTHREADS" = "Xyes"; then
    PTHREADS_CFLAGS="-D_PTHREADS_D10"
    PTHREADS_CXXFLAGS="$PTHREADS_CFLAGS"
  fi
fi
