#! /bin/sh
# /*@@
#   @file      hiuxmpp
#   @date      Wed Apr 19 17:58:22 2000
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/hiuxmpp,v 1.3 2000-07-22 16:32:41 goodale Exp $
# @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

  :

else

  CFLAGS="$CFLAGS -64"
  CXXFLAGS="$CXXFLAGS -64"

  : ${F77FLAGS="-64 -conti199 -uinline=2"}
  : ${F90FLAGS="-64 -conti199 -uinline=2"}

  LDFLAGS="$LDFLAGS -64"

  : ${C_OPTIMISE_FLAGS="-O4 -pvec -pvfunc -predicate"}
#  : ${CXX_OPTIMISE_FLAGS="-O4 -pvec -pvfunc -predicate"}

  : ${F77_OPTIMISE_FLAGS="-opt=ss -pvfunc=2 -noparallel"}
  : ${F90_OPTIMISE_FLAGS="-opt=ss -pvfunc=2 -noparallel"}

# No way to generate dependencies on this machine.
  : ${C_DEPEND="echo"}
  : ${CXX_DEPEND="echo"}
  : ${F_DEPEND="echo"}
  : ${F77_DEPEND="echo"}

  : ${C_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${CXX_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${F_DEPEND_OUT='>/dev/null ; touch $@'}
  : ${F77_DEPEND_OUT='>/dev/null ; touch $@'}

# Yet another CXX->C translator 8-(.
  : ${CXX_WORKING_NAME='$(notdir $<)'}

  : ${CXX_POSTPROCESSING='if test -r $(SCRATCH_BUILD)$(DIRSEP)$(basename $(basename $(notdir $@))).o ; then cp $(SCRATCH_BUILD)$(DIRSEP)$(basename $(basename $(notdir $@))).o $@ ; fi'}

  : ${LIBS="f90s f90 hf90pvmath hf90math m"}

# MPI stuff

  if test -n "$MPI" ; then
    NATIVE_MPI_LIBS="mpi"
    NATIVE_MPI_LIB_DIRS="/usr/mpi/lib/lib64"
    NATIVE_MPI_INC_DIRS="/usr/mpi/include"
  fi

fi







