#! /bin/sh
# /*@@
#   @file      
#   @date      
#   @author   
#   @desc 
#   
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/hp-ux,v 1.1 1999-06-14 15:50:32 allen Exp $
# @@*/

: ${LIBS="cl F90 "}
: ${LIBDIRS="+ /opt/fortran90/lib/"}
