#! /bin/sh
#  /*@@
#    @file      linux-gnulibc1
#    @date      Thu Apr 1 1999
#    @author    Gabrielle Allen
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/linux-gnulibc1,v 1.1 1999-04-01 17:13:37 allen Exp $
#  @@*/

. $srcdir/known-architectures/linux-gnu
