#! /bin/sh
#  /*@@
#    @file      osf
#    @date      Thu Mar 25 15:38:45 1999
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/osf,v 1.1 1999-04-22 13:21:59 allen Exp $
#  @@*/

: ${LIBS="for"}

