#! /bin/sh
#  /*@@
#    @file      osf
#    @date      Thu Mar 25 15:38:45 1999
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/osf,v 1.4 2001-09-04 15:02:45 allen Exp $
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${LIBS="for m"}
  : ${CXX_DEPEND='$(CXX) -E -M $(CPPFLAGS) -noimplicit_include'}

fi
