#! /bin/sh
#  /*@@
#    @file      osf
#    @date      Thu Mar 25 15:38:45 1999
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/osf,v 1.2 1999-10-11 13:49:09 goodale Exp $
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${LIBS="for"}

fi