#! /bin/sh
#  /*@@
#    @file      solaris
#    @date      Mon May 8 11:56:45 2000
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/solaris,v 1.3 2000-05-25 16:11:58 lanfer Exp $
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${LIBS="socket nsl fsu fsumai fai sunmath m"}


  : ${C_DEPEND='$(CPP) -M $(CPPFLAGS)'}
  : ${CXX_DEPEND='$(CPP) -M $(CPPFLAGS)'}


# MPI stuff

  if test -n "$MPI" ; then
    NATIVE_MPI_LIBS="mpi"
    NATIVE_MPI_LIB_DIRS="/opt/SUNWhpc/lib"
    NATIVE_MPI_INC_DIRS="/opt/SUNWhpc/include"
  fi

fi
