#! /bin/sh
#  /*@@
#    @file      solaris
#    @date      Mon May 8 11:56:45 2000
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/solaris,v 1.1 2000-05-08 10:27:54 goodale Exp $
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${LIBS="fsu fsumai fai sunmath m"}


  : ${C_DEPEND='$(CPP) -M $(CPPFLAGS)'}
  : ${CXX_DEPEND='$(CPP) -M $(CPPFLAGS)'}

fi
