#! /bin/sh
#  /*@@
#    @file      solaris
#    @date      Mon May 8 11:56:45 2000
#    @author    Tom Goodale
#    @desc 
#   
#    @enddesc
#    @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/solaris,v 1.6 2000-12-13 22:43:59 goodale Exp $
#  @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  if test -n "$F90" ; then
    SOLARIS_F90_LIBDIR="`find /opt/SUNWspro/ -name libfsu.a | grep lib/libfsu.a | tail -1 | sed -e 's:/libfsu.a::'`"
    SOLARIS_F90_LIBS="fsu fsumai fminvai fmaxvai fai sunmath"
  fi

  : ${LIBS="socket nsl $SOLARIS_F90_LIBS m ucb"}
  : ${LIBDIRS="/usr/ucb $SOLARIS_F90_LIBDIR"}


  : ${C_DEPEND='$(CPP) -M $(CPPFLAGS)'}
  : ${CXX_DEPEND='$(CPP) -M $(CPPFLAGS)'}

  : ${C_OPTIMISE_FLAGS="-O3"}
  : ${CXX_OPTIMISE_FLAGS="-O3"}
  : ${F90_OPTIMISE_FLAGS="-fast"}
  : ${F77_OPTIMISE_FLAGS="-fast"}

# MPI stuff

  if test -n "$MPI" ; then
    NATIVE_MPI_LIBS="mpi"
    NATIVE_MPI_LIB_DIRS="/opt/SUNWhpc/lib"
    NATIVE_MPI_INC_DIRS="/opt/SUNWhpc/include"
  fi

fi
