#! /bin/sh
# /*@@
#   @file   superux     
#   @date   Fri Mar 3 12:35:28
#   @author Tom Goodale  
#   @desc 
#   Known architecture stuff for the SX-5
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/superux,v 1.5 2000-03-06 18:46:21 goodale Exp $
# @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

:

else

  : ${LIBS="m"}
#  : ${LIBDIRS="/opt/fortran90/lib/"}
  : ${C_DEPEND='$(CPP) -H$@ $(CPPFLAGS)'}
  : ${CXX_DEPEND='$(CPP) -H$@ $(CPPFLAGS)'}
  : ${F77_DEPEND='$(CPP) -H$@ $(CPPFLAGS)'}
  : ${F_DEPEND='$(CPP) -H$@ $(CPPFLAGS)'}
  : ${C_DEPEND_OUT='>/dev/null 2>$(basename $(@)).d; $(PERL) -ni -e "s,^,$(basename $(@)).o $(basename $(@)).d : ,; print $_ if (! m:mismatch:) " $(basename $(@)).d'}
  : ${CXX_DEPEND_OUT='>/dev/null 2>$(basename $(@)).d; $(PERL) -pi -e "s,^,$(basename $(@)).o $(basename $(@)).d : ,; print $_ if (! m:mismatch:) " $(basename $(@)).d'}
  : ${F_DEPEND_OUT='>/dev/null 2>$(basename $(@)).d; $(PERL) -pi -e "s,^,$(basename $(@)).o $(basename $(@)).d : ,; print $_ if (! m:mismatch:) " $(basename $(@)).d'}
  : ${F77_DEPEND_OUT='>/dev/null 2>$(basename $(@)).d; $(PERL) -pi -e "s,^,$(basename $(@)).o $(basename $(@)).d : ,; print $_ if (! m:mismatch:) " $(basename $(@)).d'}

fi
