#! /bin/sh
# /*@@
#   @file    superux
#   @date    Fri Mar 3 12:35:28
#   @author  Tom Goodale
#   @desc
#            Known architecture stuff for the SX-5
#   @enddesc
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/superux,v 1.13 2003-09-24 15:30:04 tradke Exp $
# @@*/

if test "$CCTK_CONFIG_STAGE" = 'preferred-compilers' ; then

:

else

  # c++ compiler doesn't accept the '-O2' option
  : ${CXX_OPTIMISE_FLAGS='-O'}

  : ${LIBS='i90sx f90sxe v90sxe_sv i90sxe m90sxe m'}

  # dependencies are a bit awkward to generate
  : ${C_DEPEND='$(CPP) -H$@ $(CPPFLAGS)'}
  : ${CXX_DEPEND='$(C_DEPEND)'}
  : ${F77_DEPEND='$(C_DEPEND)'}
  : ${F_DEPEND='$(C_DEPEND)'}
  : ${C_DEPEND_OUT='> /dev/null 2> $(basename $(@)).d; $(PERL) -ni -e "s,^,$(basename $(@)).o $(basename $(@)).d : ,; print if (! m/:.*:/) " $(basename $(@)).d'}
  : ${CXX_DEPEND_OUT='$(C_DEPEND_OUT)'}
  : ${F_DEPEND_OUT='$(C_DEPEND_OUT)'}
  : ${F77_DEPEND_OUT='$(C_DEPEND_OUT)'}

  # MPI stuff
  if test -n "$MPI" ; then
    NATIVE_MPI_LIBS='mpi'
  fi
fi
