#! /bin/sh
# /*@@
#   @file      unicos
#   @date      Thu Feb 25 09:53:22 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/unicos,v 1.1 1999-04-08 19:31:21 goodale Exp $
# @@*/

# The T3E F90 compiler uses -b if you want to supply a name for a .o file.
: ${FCOMPILEONLY="-b"}

