#! /bin/sh
# /*@@
#   @file      unicos
#   @date      Thu Feb 25 09:53:22 1999
#   @author    Tom Goodale
#   @desc 
#   
#   @enddesc 
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/known-architectures/unicosmp,v 1.2 2004-03-28 21:03:03 goodale Exp $
# @@*/

if test "$CCTK_CONFIG_STAGE" = "preferred-compilers" ; then

  if test -z "$F90"; then
    F90="ftn"
    echo Setting Fortran 90 compiler to $F90
  fi
  if test -z "$F77"; then
    F90="ftn"
    echo Setting Fortran 77 compiler to $F77
  fi

else

  : ${CFLAGS=""}
  : ${CXXFLAGS=""}
  : ${C_OPTIMISE_FLAGS="-O3"}
  : ${CXX_OPTIMISE_FLAGS="-O3"}
  : ${F90_OPTIMISE_FLAGS="-O 3"}
  : ${F77_OPTIMISE_FLAGS="-O 3"}
  : ${C_DEBUG_FLAGS="-g"}
  : ${CXX_DEBUG_FLAGS="-g"}
  : ${F77_DEBUG_FLAGS="-g"}
  : ${F90_DEBUG_FLAGS="-g"}
  : ${C_WARN_FLAGS="-h msglevel_0"}
  : ${CXX_WARN_FLAGS="-h msglevel_0"}
  : ${F77_WARN_FLAGS="-m 0"}
  : ${F90_WARN_FLAGS="-m 0"}

  # The T3E fortran compiler puts module info in .o files by default.
  # : ${F90FLAGS="-dp -em"} 

# Cache stuff
  if test -z "$CACHELINE_BYTES" ; then
    CACHELINE_BYTES=16
    echo "Setting CACHELINE_BYTES to $CACHELINE_BYTES"
  fi

  if test -z "$CACHE_SIZE" ; then
    CACHE_SIZE="512*1024"
    echo "Setting CACHE_SIZE to $CACHE_SIZE bytes"
  fi

# MPI stuff

  if test -n "$MPI" ; then
#   Don't need to set anything for compiling with native MPI on the T3E
#   We just set NATIVE_MPI_LIBS to non-null so that it passes the
#   check in lib/make/extras/MPI/NATIVE.
    NATIVE_MPI_LIBS=" "
  fi

fi

